package com.vladmihalcea.hibernate.type.util;

import org.hibernate.query.internal.AbstractProducedQuery;

import javax.persistence.Query;
import java.util.Collections;

/**
 * <code>SQLExtractor</code> - Query utilities holder.
 *
 * @author Vlad Mihalcea
 * @since 2.9.11
 */
public class SQLExtractor {

    private SQLExtractor() {
        throw new UnsupportedOperationException("SQLExtractor is not instantiable!");
    }

    /**
     * Get the underlying SQL generated by the provided JPA query.
     *
     * @param query JPA query
     * @return the underlying SQL generated by the provided JPA query
     */
    public static String from(Query query) {
        AbstractProducedQuery abstractProducedQuery = query.unwrap(AbstractProducedQuery.class);
        String[] sqls = abstractProducedQuery
            .getProducer()
            .getFactory()
            .getQueryPlanCache()
            .getHQLQueryPlan(abstractProducedQuery.getQueryString(), false, Collections.emptyMap())
            .getSqlStrings();

        return sqls.length > 0 ? sqls[0] : null;
    }
}
