package io.hypersistence.utils.hibernate.query;

import jdk.jfr.Event;
import jdk.jfr.Category;
import jdk.jfr.Label;
import jdk.jfr.Description;

@Category("Hibernate")
@Label("Query")
class QueryEvent extends Event {

  @Label("SQL")
  @Description("The SQL query generated by Hibernate")
  private String sql;

  String getSql() {
    return sql;
  }

  void setSql(String sql) {
    this.sql = sql;
  }

}
